# Generated by Django 3.0.3 on 2021-02-16 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity_logger', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='activity',
        ),
        migrations.AddField(
            model_name='activity',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='activity_logger.Users'),
        ),
    ]
